"""task user

Revision ID: 038b625a6883
Revises: c4d23a67e729
Create Date: 2023-12-30 05:37:29.994580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038b625a6883'
down_revision = 'c4d23a67e729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
