"""User fields

Revision ID: ae5c9b32fc1f
Revises: 91c32f5bea6b
Create Date: 2023-12-27 05:57:10.589955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5c9b32fc1f'
down_revision = '91c32f5bea6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('email_cofirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('avatar_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'documents', ['avatar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('avatar_id')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('email_cofirmed_at')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
