"""lang user

Revision ID: c4d23a67e729
Revises: 3636cf87a756
Create Date: 2023-12-30 05:33:09.195598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d23a67e729'
down_revision = '3636cf87a756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.Enum('ES', 'EN', name='langchoices'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lang')

    # ### end Alembic commands ###
